INSERT INTO COURSE (COURSEID, NAME, CODE) VALUES (1, 'Course 1', '100');
INSERT INTO COURSE (COURSEID, NAME, CODE) VALUES (2, 'Course 2', '200');
INSERT INTO COURSE (COURSEID, NAME, CODE) VALUES (3, 'Course 3', '300');
